INSERT INTO BOOK( ISBN, BOOK_NAME, PRICE ) VALUES( '0001', 'The First Book', 30);
INSERT INTO BOOK_STOCK(ISBN, STOCK) VALUES('0001', 30) ;
INSERT INTO ACCOUNT(USERNAME, BALANCE) VALUES('user1',2000);


INSERT INTO BOOK( ISBN, BOOK_NAME, PRICE ) VALUES( '0002', 'The First Book', 30);
INSERT INTO BOOK_STOCK(ISBN, STOCK) VALUES('0002', 0) ;
